### ISSUE TITLE
[Time Conductor] Continuing Historical/Real-time reconciliation

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#1091]
Moved from #1089
- [x] ~~1. Add support for formats to the `delta` fields. Currently uses a new `duration` format which will only work for hh:mm:ss, not sols. Though, do we need to support anything else in the delta fields right now?~~ Addressed in separate issue #1225 
- [x] 2. Support new time conductor from legacy plots. This is partially supported through telemetry decorator, but plot should tick with time conductor not data availability.
- [x] ~~3. Improve tick labelling. Currently tick label formatting can be a little unclear.~~- Addressed in separate issue #1345
- [x] ~~4. Time systems without defaults totally break the time conductor~~ Addressed in separate issue #1344
- [x] ~~5. Ticks overlap when scale formatting is not available (recommend deferring)~~ - Addressed in separate issue #1345
- [x] ~~6. Removal of compatibility layer~~ Addressed in separate issue #1343
- [x] ~~7. Support for setting mode and tick sources via API.~~ Addressed in separate issue #1265

**Comment by larkin** [comment]
Pushed to roddenberry as a set of potential stability / cleanliness improvements.

**Comment by larkin** [comment]
Some of this may feed into time conductor API additions to public API.

**Comment by akhenry** [comment]
Split into separate issues
