### ISSUE TITLE
Vue front-end todos

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2178]
A general holder issue for front-end-related items.

### Todos
- [ ] What happened to the "NOW" clock display in Conductor RT mode in the Vue conversion?
- [x] Complete overlay in mobile.
- [ ] Fix List Vue cell ellipsis, not working currently. 
- [ ] Hide List Vue columns in mobile portrait mode.
- [x] Hide Preview button when object is in main view, i.e. not in `.c-frame`.
- [x] Fix folder Grid view alias indicators in mobile - they're not being transformed currently.

### Done, needs someone else to pick up
- [x] Fix Datepicker / modalMenu elements in mobile. **DONE**; file PR for branch vue-conductor-mobile.
- [ ] Add alias indication to tree items. **DONE**, but needs to be wired up.

**Comment by larkin** [comment]
@charlesh88 I'm moving these over to the large checklist in https://github.com/nasa/openmct/pull/2140 and closing this.
