### ISSUE TITLE
Conditionals Testathon 2 March 26, 2020 Issues

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#2796]
### High
- [x] Add support for NOT and XOR in Match, with "when no criteria are met" and "when only one criteria is met". Tracking in #2811
- [x] Numeric evaluations greater than  / less than are failing to match:
![Screen Shot 2020-03-26 at 4 35 33 PM](https://user-images.githubusercontent.com/1056412/77706522-dac38d80-6f7f-11ea-9b0d-08b3cc7ee36e.png)
  - @shefalijoshi has the fix here, cast comparison as Number().
- [x] Handle mixed conditional styling when selecting multiple objects in a Layout #2744.
- [x] After defining a criteria out to the comparison level:
![Screen Shot 2020-03-26 at 5 00 40 PM](https://user-images.githubusercontent.com/1056412/77707844-9b973b80-6f83-11ea-856a-492e39e47517.png)
and then changing the field to another data type (from number to string) causes the comparison select to not initialize properly and the input to to receive a CSS class as its type (!)
![Screen Shot 2020-03-26 at 5 00 51 PM](https://user-images.githubusercontent.com/1056412/77707852-a520a380-6f83-11ea-8f0b-7c8dba948d72.png)
- [x] Duplicating Conditions results in a criterion changes in one condition being applied to another criterion as if they were the very same.
- [x] Test data is still not complete
- [x] Resizing and/or repositioning drawing objects and them immediately changing a style attribute in the Inspector causes the drawing object to reset to its previous pose. Main toolbar interactions for same don't exhibit this behavior. 
![Screen Shot 2020-03-24 at 3 25 10 PM](https://user-images.githubusercontent.com/1056412/77482652-b0d56400-6de3-11ea-9e55-43bfa0e01d08.png)
- [x] @charlesh88 Remove Image URL button from main Display Layout toolbar.
- [x] "No output selected" still displays after even after configuring the default condition: 
![Screen Shot 2020-03-26 at 3 22 01 PM](https://user-images.githubusercontent.com/1056412/77702439-c1b5df00-6f75-11ea-8c5a-a575d21ff19f.png) See #2774. 

### Medium
- [x] Changing a criteria test (greater than / less than / etc.) should not blank out input fields. In general, try to preserve all user input where possible.
- [X] 'any | all telemetry' in the 'when' row not yet implemented.
- [x] While editing, Conditions should be clickable to apply their style settings.
- [x] Dynamic condition evaluation and style application should be suspended while editing an object.
- [x] Currently matched Condition is not visually highlighting.
- [x] When editing a Condition Set, the view switcher control from Conditions View to Telemetry Table is available, but shouldn't be. See #2867.
![Screen Shot 2020-03-26 at 2 48 30 PM](https://user-images.githubusercontent.com/1056412/77700463-77326380-6f71-11ea-924a-b8079c170edc.png) 

### Low
- [ ] Drag reorder in Condition Set needs to be improved.
- [x] Summary Widgets and Hyperlink objects should disallow domain object styling, both static and conditional.
- [ ] Add a Confirmation dialog when removing a Condition Set from an object.
