### ISSUE TITLE
Allow user to select and apply font size and family as a style option

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#3196]
Allow the user to select and apply font-size and font-family to Display Layout. Work happening in branch TBD; previously some font-sizing work done by @deeptailor in `styling-font-sizes-060920`.

### Overview
Both font size and family style options will only be available for object views in a Display Layout, from the toolbar. Certain object types will be supported; Display and Flexible Layouts, as well as Tab Views will _not_ get these properties as a style option, i.e. selecting a sub-layout while editing a layout will not display the font size or family toolbar button.

### Multi-select
For multi-selected mixed setting cases, we decided that the font-size and family buttons should get the `c-icon-button--mixed` style if either a) the selection includes the same type of elements, but they use different settings OR b) the selection includes elements that can accept the style (table, plot) and those that can't (nested layouts, Tab Views). In this case, we follow the same pattern as elsewhere in that the style is settable, but items that don't accept that styling ignore the setting. 

### Font Size
Font size to be implemented as a series of classes to allow easier exclusion of elements that shouldn't be affected. Digging more into implementation, inline user-controlled styling is currently applied in the following locations:
- Overlay plot, plot view: styles are applied to l-angular-ov-wrapper which includes the JPG/PNG and cursor guides buttons.
- Tables: styles are applied to c-table-wrapper which includes the control bar buttons.
- Other views TBD

Class naming should follow this convention: "is-font-size--<size>px". So: 
- is-font-size--8px
- is-font-size--36px
- etc.

The following table lists desired font sizes for the current object types:

Size|Alphas, Text, Cond Widgets, Clocks/Timers, Notebooks|Tables, Plots
----|----|----
8px|Y|Y
9px|Y|Y
10px|Y|Y
11px|Y|Y
12px|Y|Y
13px|Y|Y
14px|Y|Y
16px|Y|Y
18px|Y|Y
20px|Y|Y
24px|Y|Y
28px|Y|
32px|Y|
36px|Y|
42px|Y|
48px|Y|
72px|Y|
96px|Y|
128px|Y|

### Font Families
Apply in style tag like this: `style="<style-string>"`. The default selection should be Default (as below). If no other style is applied (background, foreground, etc.) then the style attribute should be removed entirely.
- [x] Define font-families - @charlesh88.
- [x] Create new icon glyph or other visual approach for font-family button - @charlesh88.
- [x] Wire it up - @deeptailor 

Name | 'data-font=' String | Description
---- | ---- | ----
Default | default | Theme's built-in font
Default Bold | default-bold | Bolds theme's built-in font
Narrow |  narrow | Narrow font
Narrow Bold | narrow-bold | Narrow font bold
Monospace | monospace | Monospace font
Monospace Bold | monospace-bold | Monospace font bold

Useful font resource here: https://www.cssfontstack.com/.

**Comment by charlesh88** [comment]
07/15/2020: After discussion with @deeptailor we've decided that, as an initial implementation, font-family (and font-size as well) should be limited to frame elements within a Display Layout. The rationale here is that font-family and font-size really do not want to change conditionally, and therefore don't belong in the Inspector-based Styling interface.

**Comment by charlesh88** [comment]
Digging more into implementation, inline user-controlled styling is currently applied in the following locations:

- Overlay plot, plot view: styles are applied to `l-angular-ov-wrapper` which includes the JPG/PNG and cursor guides buttons.
- Tables: styles are applied to `c-table-wrapper` which includes the control bar buttons. 

What's going on of course is that styles are being applied at a particular point to object views. It would be better for the styles to be able to applied deeper within the view, in a way that the view could control the location of application. @deeptailor let's discusss.

**Comment by charlesh88** [comment]
Have pushed some significant changes:

### Changes
- CSS completed, using `data-*` attributes to set font-size and family;
- New `u-style-receiver` class for use as font-size and font-family CSS selector target;
- Added `getStyleReceiver` method, and changes to `updateStyle` and `setFontSizre` methods in ObjectView.vue;
- New `js-style-receiver` class for use as JS target by ObjectView.vue, changes to ;
- New classes added to markup in all Open MCT views;
- Changed font-size values from 'is-font-size--*' to just the number;
- Some refinement to individual views to account for font-sizing capability;
- Removed automatic font-size 13px being set by SubobjectView.vue;

### Todos
- [ ] Add font-family selection per above to Layout toolbar;
- [ ] Font-size needs to be changed in Layout drawing objects to use new data-* approach rather than inline styles;
- [ ] Layout multi-select doesn't work properly for font sizing when selecting a mix of drawing and domain objects;
- [ ] Lots of unit testing!

**Comment by deeptailor** [comment]
@charlesh88 - I think we are almost done right?

**Comment by charlesh88** [comment]
> @charlesh88 - I think we are almost done right?

I'm not yet seeing table row heights respond to font sizing, and that's a must-have.

**Comment by charlesh88** [comment]
As of Testathon 11-02-20, this is resolved.
