### ISSUE TITLE
[User Requests] Improved Time Conductor inputs

### ISSUE THREAD

**Issue by jvigliotta** [nasa/openmct#3311]
Provide the user with a more intuitive way to input time for the time conductor.

**Comment by charlesh88** [comment]
### Todos @jvigliotta:
- [ ] Implement Enter key to apply values and dismiss bubble; make Esc cancel. [UT-OCT20-02]
- [ ] Move "up" arrow down one level, so My Items would not have a nav up arrow. [UT-OCT20-04]
- [ ] Handle clicks outside the input bubble: implement an outside click handler that cancels input and dismisses the input. [UT-OCT20-08]

### Todos @charlesh88 
- [ ] Change current range settings from inputs to clickable-looking elements [UT-OCT20-01]
- [ ] Change "up" arrow glyph to use "nav-to-parent" icon. [UT-OCT20-04]
- [ ] Try removing leading 00's from inputs, just use numbers AND/OR try adding zero padding on keydown, with zero padding grayed down. [UT-OCT20-12]
- [ ] Include valid entry ranges in tooltips on inputs [UT-OCT20-14]

**Comment by jvigliotta** [comment]
@charlesh88 added these features

**Comment by charlesh88** [comment]
### Testing Notes
1. Navigate to a plot view or layout that includes time-based telemetry.
2. Set the Time Conductor to Local UTC to enable real-time mode.
3. Ensure that the conductor looks like this: 
![Screen Shot 2021-01-26 at 3 17 24 PM](https://user-images.githubusercontent.com/1056412/105918987-b72b0280-5fe9-11eb-9c82-29a91a535896.png)
4. Click the Start time button, and verify that a popup interface is displayed:
![Screen Shot 2021-01-26 at 3 17 41 PM](https://user-images.githubusercontent.com/1056412/105919103-df1a6600-5fe9-11eb-8940-8b47cde1deed.png)
5. Verify that that the "HRS" field's value is pre-selected.
6. Verify that tooltips appear for each input as you hover and dwell over each.
7. Enter some valid values in the fields based on displayed tooltips, then click the "check" button to apply the entered offset.
8. Verify that the Start time button is updated properly, that Time Conductor ticks and visible telemetry displays as expected.
9. Repeat steps 4 through 8 for a few different valid values.
10. Repeat steps 4 through 8, but enter invalid values. Verify that the fields with bad values display in red and the "check" button is disabled and won't allow the popup to be dismissed:
![Screen Shot 2021-01-26 at 4 12 16 PM](https://user-images.githubusercontent.com/1056412/105923525-5acbe100-5ff1-11eb-8f6d-5006a2b2a052.png)

**Comment by akhenry** [comment]
Closed by #3409

**Comment by kobe1104** [comment]
Hitting the ESC key doesn't close the popup. Besides that all are working. Testathon 6/22/21.

**Comment by charlesh88** [comment]
Verified Testathon 06-22-2021
