### ISSUE TITLE
Search improvements

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#3406]
1. [ ] ~~Add type to indexed objects (so that minimal objects are returned with id, name, type, which is sufficient to render items in tree)~~ #3407 
2. [ ] ~~Modify tree to fetch objects before allowing context action click, and on drag and drop. #3408~~ 
3. [x] Add search to object API #3609 (see code stubs in https://github.com/nasa/openmct/compare/search-api-stubs)
4. [x] [Implement search in Couch DB](https://github.com/nasa/openmct/issues/3218) ~~Hold off on this until we make a decision about persistence~~
5. [x] [Implement search in YAMCS](https://github.com/akhenry/openmct-yamcs/issues/19)

**Comment by davetsay** [comment]
do we need this anymore @akhenry , @jvigliotta ?

**Comment by akhenry** [comment]
Closed because everything was either done or spun off into separate issues.
