### ISSUE TITLE
[e2e] e2e testing Epic

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#4458]
### Considerations which are specific to `openmct`
- linting
- percy
- browserstack
- ipad
- codecoverage

### Implementation Roadmap

- [ ] Find a e2e testing tool which serves as a visual regression testing tool and client-side performance measurement tool
- [ ] Implement POC for automated performance testing
- [ ] Implement POC for e2e testing
- [ ] Implement smoke tests
- [ ] Implement visual regression smoke tests
