### ISSUE TITLE
Flexible layouts are not tracking changes in sub objects

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4773]
Originally reported as https://github.com/nasa/openmct/issues/4737#issuecomment-1020632100

#### Summary
Flexible layouts are not tracking any changes in sub-objects. This is probably because they are not passing a `MutableDomainObject` down to their sub-object views, [unlike Display Layouts](https://github.com/nasa/openmct/blob/7703ec0a614324f84c24a9e08345a37ed6d9c61e/src/plugins/displayLayout/components/SubobjectView.vue#L134).

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [X] Is there a workaround available?
- [X] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?

#### Steps to Reproduce
1. Open a flexible layout
2. Expand the flexible layout in the tree
3. Right click on an object in the layout from the tree and use the properties dialog to rename it
4. Observe that the name updates in the tree, but not in the flexible layout.
5. Now renamed an object in the flexible layout
6. Note that the name changes in the flexible layout and in the tree.

Repeat the steps above in a display layout and observe that renaming objects works in both directions.

#### Environment
* Open MCT Version: 1.8.4
* Deployment Type: VIPER Testathon

**Comment by akhenry** [comment]
Marking critical because of its impact on multi-user notebooks.

**Comment by charlesh88** [comment]
This also manifests when an object in a Flex Layout is removed via the tree. The tree will show the updated composition, but when viewing the layout the removed object is still present.

**Comment by akhenry** [comment]
## Testing instructions

#### Verify that new notebook entries work from flexible layouts:

1. Open a flexible layout that contains a notebook
2. Open the same notebook in a separate tab or window so that both the flexible layout and the notebook are open at the same time
3. Add an entry to the notebook within the flexible layout, and verify that it appears in the same notebook in a separate tab
4. Add an entry to the notebook in a separate tab and verify that the entry appears in the notebook inside the flexible layout.

#### Verify that composition changes are reflected in a flexible layout

1. Open a flexible layout
2. From the tree, remove one of the children of the flexible layout by right clicking and selecting the "Remove" action
3. Verify that the removed child disappears from the flexible layout.

#### Verify that renaming objects in a flexible layout works:

1. Open a flexible layout
2. Expand the flexible layout in the tree
3. Right click on an object in the layout from the tree and use the properties dialog to rename it
4. Observe that the name updates in the tree, but not in the flexible layout.
5. Now renamed an object in the flexible layout
6. Note that the name changes in the flexible layout and in the tree.

**Comment by khalidadil** [comment]
When I rename an object in the tree (outside of a flexible layout), the name of the reference to the object inside of the flexible layout is also updated. This behavior makes sense, but the testing instructions say `Observe that the name updates in the tree, but not in the flexible layout`. Is this right @akhenry?

All of the other tests work - verified in testathon on 01/26/22

**Comment by nikhilmandlik** [comment]
Verified Fixed.

**Comment by charlesh88** [comment]
> When I rename an object in the tree (outside of a flexible layout), the name of the reference to the object inside of the flexible layout is also updated. This behavior makes sense, but the testing instructions say `Observe that the name updates in the tree, but not in the flexible layout`. Is this right @akhenry?

@khalidadil The test instructions for that section are a copy/paste error: renaming something from the tree should update all instances of that object, everywhere. I have corrected the instructions.

**Comment by akhenry** [comment]
>  The test instructions for that section are a copy/paste error: renaming something from the tree should update all instances of that object, everywhere. I have corrected the instructions.

Oh, dang, yeah, sorry. Good catch. 🤦 Thanks @charlesh88

**Comment by charlesh88** [comment]
Verified fixed Testathon 1/26/22:
- [x] Notebook updates in Flex Layouts
- [x] Remove from tree
- [x] Renaming, both directions AND for the bonus win, renaming existing pages and sections.

Nice work!
