### ISSUE TITLE
[Plots] Reduce space used by independent Time Conductors

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#4975]
**Is your feature request related to a problem? Please describe.**
We should use less vertical space for displaying independent time conductors (and the toggle button) in plots.

MORE DETAIL NEEDED

**Comment by shefalijoshi** [comment]
@charlesh88 Please elaborate on UI changes here.

**Comment by charlesh88** [comment]
Design in progress...

**Comment by charlesh88** [comment]
Writeup and clickable mockup now available in the VIPER Open MCT Confluence area in "Space Optimization & Compact Time Conductor".

**Comment by charlesh88** [comment]
### Todos
Discussed with Shefali today:
#### @charlesh88 
- [ ] Markup and styling for "read-only" ITC views.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/1056412/168333082-434c968b-bd6b-44f0-8688-4d8e03c412ab.png">
<img width="447" alt="image" src="https://user-images.githubusercontent.com/1056412/168333147-e4316c3a-1033-48f2-bd04-9d73a3e83eab.png">

- [ ] Time Control symbols font glyph (?)


#### @shefalijoshi 
- [ ] Move controls into hover menu element per design.
- [ ] Any needed reactive wiring in ITC views.

**Comment by charlesh88** [comment]
Work started in local branch `time-conductor-4975`.

**Comment by akhenry** [comment]
@shefalijoshi @charlesh88 This ready for Build 6 feature freeze?

**Comment by charlesh88** [comment]
### Todos 2023
- [ ] @shefalijoshi Current time in Local Clock (shown as 'LAST UPDATE') has the old problem of including the future time offset. This was fixed in #6405, let's make sure we don't regress this.
- [ ] @shefalijoshi Menu removal on outside clicks needs refinement, user must click twice to remove the Mode supermenu and the timeframes popup, but should only have to click once outside. Also, clicking on the timeframes popup while the supermenu should hide it, but currently doesn't.
- [ ] @shefalijoshi ITC's don't show the mode choice button when the TC is in Local Clock, but should. If you toggle the main TC to Fixed, and then back to Local, the ITC will show the mode choice button.
- [ ] Switching the ITC to Fixed mode doesn't actually switch it, but should.
- [ ] @charlesh88 Better approach to display in the ITC when frame width is very constrained. 
  - [ ] The title of small frames is getting very compressed when the ITC is expanded, which shouldn't happen. 
  - [ ] The collapsed ITC shows the gear icon, but instead should be showing the TC icon. Suggest just killing the gear if the frame is "--width-less-than-600" or when the frame is hidden. Also, make sure we have a really compact strategy when "--width-less-than-220".

**Comment by charlesh88** [comment]
### Testing Notes
See #5773.
