### ISSUE TITLE
[e2e] Refactor our extension of existing playwright APIs and playwright RFE APIs

### ISSUE THREAD

**Issue by unlikelyzero** [nasa/openmct#5523]
#### Summary
We're nearing the point in our test framework implementation where we'll need to define how common functions should be exposed, used, and added to our test suite.

#### Tasks
- [x] Rename commonActions.js to appActions.js and keep in root folder. Add note about https://www.cypress.io/blog/2019/01/03/stop-using-page-objects-and-start-using-app-actions/
- [x] Renambe fixtures.js to _something which is obvious that it extends base fixtures. @ozyx to investigate. I think they use baseFixtures.js in their examples.  
- [x] Update documentation to be specific that only functions which extend the base playwright/test functionality go here. Any additional functions which are explicitly for those functions should be marked as private (codecoverage example).
- [x] Collect all examples of functions which extend the base functionality of playwright/test into fixtures.js. Off the top of my head, these functions are currently found in commonActions.js (waitForAnimationsToFinish) and visual test suites which manipulate the clock. 
- [x] Move all RFE APIs (APIs which existing a feature requests in the official playwright repo) should also be moved to a specific location like `./fixtures.js` or `./commonActions.js`
- [x] Document the above in our readme and within the file itself
- [x] Create a new function called 'getOrCreateDomainObject' for generating objects and returning the uuid
- [x] Update ts codehints and document heavily within this document and the readme
