### ISSUE TITLE
Time Conductor issues Testathon 7/19/23

### ISSUE THREAD

**Issue by charlesh88** [nasa/openmct#6811]
@charlesh88 filed all the below as separate issues as noted.

#### Summary
Several issues found in Time Conductor:
- [ ] Disabling the independent Time Conductor while the settings popup is visible causes the ITC to toggle close but appear to still be active. When subsequently re-enabling, the settings popup will not be shown on click. @rukmini-bose: I see this behavior happening even when the independent Time Conductor is enabled and you're simply changing the time settings and **saving**. Basically, what I'm seeing is that any time you make any changes to the ITC and save, you cannot view the popup again upon a second click. You'd have to refresh to see it again. @shefalijoshi blocker Filed as #6826.
- [ ] Notebook Snapshot's "Navigate to Item in Time" is not working as expected: Snapshotting a plot in a layout frame and then clicking the "Navigate to Item in Time" will take the user to the _layout_, not the plot as it should. What should happen is the user is taken to the plot in the main view with the main TC set to the timeframe of the Snapshot, which should be based on whatever independent TC settings were in place at the time. (regression? retest) - critical Filed as #6827.
- [ ] The Remote clock periodically freezes ticking, then starts again. This happens frequently. @jvigliotta blocker Filed as #6828.
- [ ] The TC is broken visually in Safari @charlesh88 medium 
  - [ ] When invoking the inputs popup the whole screen layout is severely broken. This should be looked at in the context of mobile. 
  - [ ] In Fixed mode, the tick labels disappear after zooming or panning. Filed as #6829.
- [ ] The clock indicator in the Status area blinks rapidly between different values when the main TC is using Local Clock. @ozyx **DELETE THE CLOCK INDICATOR** medium
- [ ] Header elements sometimes do not update after using the ITC: After using the ITC in Imagery layout, if you navigate to another object (I'm able to reproduce this consistently with an Overlay Plot), the "Imagery Layout" button still appears in the header. And note, this Imagery Layout remains in the header for any other objects you navigate to until you refresh. @shefalijoshi critical Added to #6826.
<img width="1086" alt="Screen Shot 2023-07-19 at 11 20 32 AM" src="https://github.com/nasa/openmct/assets/48999852/5e2d78e2-7fbe-46be-8a2d-8d1de8c5b762">

#### Steps to Reproduce

1.
2.
3.
4.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [ ] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [ ] Does this impact a critical component?
- [ ] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by shefalijoshi** [comment]
Closed since individual issues were created for this list.
