### ISSUE TITLE
Fix failing e2e tests

### ISSUE THREAD

**Issue by akhenry** [nasa/openmct#6814]
#### Summary
* [x] notification: @davetsay disabled, #6820
* [x] recentObjects: @davetsay disabled, #6818
* [x] flexibleLayout: @akhenry
* [x] search : @akhenry 
* [x] exampleImagery @ozyx 
* [x] notebook @ozyx 
* [x] ~restrictedNotebook~ @shefalijoshi  (No failing tests found)
* [x] tags @shefalijoshi 
* [x] autoscale @shefalijoshi 
* [x] logPlot @shefalijoshi  
* [x] tagging  @khalidadil - disabled, #6822
* [x] telemetryTable @shefalijoshi  
* [x] timeConductor @shefalijoshi - history not saved on URL timebounds change #6824
* [x] displayLayout: @shefalijoshi Removing an item from composition isn't working
* [x] clocks: @shefalijoshi 
* [x] timeStrip: @shefalijoshi

**Comment by akhenry** [comment]
Working out of https://github.com/nasa/openmct/compare/e2e-test-fixes

**Comment by khalidadil** [comment]
@ozyx Where were we on this? It sounded like the branch is almost ready to be merged?

**Comment by ozyx** [comment]
> @ozyx Where were we on this? It sounded like the branch is almost ready to be merged?

Yeah, we are almost there. There are a few new failures that cropped up that we will need to fix. We should be able to get the branch merged by EOD today I’d think.
