### ISSUE TITLE
Our <meta> tags are not being loaded in the DOM

### ISSUE THREAD

**Issue by rukmini-bose** [nasa/openmct#7373]
#### Summary

We have 3` <meta>` tags in our viewport source code, allowing us to have better accessibility. However, when loading Open MCT, it seems like only one of the tags is being shown. This will greatly impact our overall accessibility when it comes to supporting different devices.
 
#### Expected vs Current Behavior

This is our current code for our `<meta> `tags in `index.html`. 
```
<meta charset="utf-8" />
<!-- Modified viewport meta tag to improve accessibility -->
<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />
```
However, when loading Open MCT on a browser, the console shows only the following tag. 
`<meta charset="utf-8" />`

Because the other two are not being loaded, we are not going to be compliant with different device sizes, as the other two <meta> tags allow for dynamic sizing depending on our device size. This is a major problem, as we are currently trying to improve mobile accessibility. 

We need to investigate to why, even though our source code shows the tags, they are not being loaded in. Is something causing them to be overwritten? It is a browser issue? 

Observation from 1/16/2023: this issue does not happen when running Open MCT locally. 
#### Steps to Reproduce

1. Load Open MCT on your browser (I am using Chrome).
2. Open the Console and look at the DOM. 
3. Under the `<head>` tag, observe that the **only**` <meta>` tag that appears is `<meta charset="utf-8" />`.

#### Environment

* Open MCT Version: 
* Deployment Type: 
* OS:
* Browser:

#### Impact Check List

- [ ] Data loss or misrepresented data?
- [x] Regression? Did this used to work or has it always been broken?
- [ ] Is there a workaround available?
- [x] Does this impact a critical component?
- [x] Is this just a visual bug with no functional impact?
- [ ] Does this block the execution of e2e tests?
- [ ] Does this have an impact on Performance?

**Comment by ozyx** [comment]
Were you looking at a VIPER deployment of Open MCT possibly? That uses a different `index.html`, which is missing those extra `<meta>` tags. When I launch Open MCT locally, I do see those tags.

**Comment by rukmini-bose** [comment]
> Were you looking at a VIPER deployment of Open MCT possibly? That uses a different `index.html`, which is missing those extra `<meta>` tags. When I launch Open MCT locally, I do see those tags.

Yes, that's correct. Our VIPER deployment should have the same `<meta>` tags as well. Let's move this internally then?

**Comment by ozyx** [comment]
> > Were you looking at a VIPER deployment of Open MCT possibly? That uses a different `index.html`, which is missing those extra `<meta>` tags. When I launch Open MCT locally, I do see those tags.
> 
> 
> 
> Yes, that's correct. Our VIPER deployment should have the same `<meta>` tags as well. Let's move this internally then? 

Yep! Should be a quick fix.

**Comment by rukmini-bose** [comment]
This issue has been completed and merged internally.

**Comment by rukmini-bose** [comment]
Testing Notes: 
1. Load Open MCT, open the console, and use the emulator to switch to mobile. 
2. Refresh. 
3. Now go to the DOM, and ensure that the new <meta> tags recognize Open MCT as being in mobile and the tags match the following: 

`<meta charset="utf-8" />

<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />`

**Comment by ozyx** [comment]
Verified fixed -- Testathon 3/28/24
