### ISSUE TITLE
Derived Telemtry Prototype

### ISSUE THREAD

**Issue by scottbell** [nasa/openmct#7823]
**Is your feature request related to a problem? Please describe.**
Create a new objected in Open MCT that supports a user entered expression (in math.js format) and outputs the result of that expression as telemetry.

**Comment by charlesh88** [comment]
In progress notes while working in the branch:
- [ ] Doesn't currently work with Sine Wave Generators.
- [ ] Setting test values a = 1 and b = 2 with expression a*b = 2, but changing a to 0 outputs "---" when I would have expected 0.

**Comment by charlesh88** [comment]
Changes so far:
- New component `/ui/components/ObjectPathString.vue` used instead of ObjectPath.
- Layout, styling cleanups.
- Test values section of telemetry ref elements now hidden when not in edit mode.
- Tweaks to messaging.
- Removed error icon applied to main holder.

**Comment by charlesh88** [comment]
### Todos
@charlesh88 
- [ ] Continue style refinements, particularly code validation / error message area.
- [ ] Refine main 'output' field at top of UI to better handle long values, like arrays.

**Comment by scottbell** [comment]
Great work @charlesh88! I think I addressed the issues you described, and am working toward some e2e tests now. One question though: do we want to make the expression itself more prominent? It's rather small now, and is probably the main thing I want to be looking at when I bring up the view?

**Comment by charlesh88** [comment]
Agree on the smallness of the expression; gave it a monospace font which looks bigger and is just better. Have pushed what I think are near complete changes for derived telemetry:
- Final sanding and polishing.
- New discrete item style `c-output-featured` added to controls.scss.
  - Applied to 'Current Output' section of both Derived Telemetry and Condition Sets.
- Added icons and styling to expression validation message. Message now shows in browse mode if invalid.
- Monospace font used in expression input and browse mode display.

### TODOs:
- [ ] Check for low-risk regressions in Condition Sets browse and edit modes.
- [ ] New tests for ObjectPathString.vue component.

**Comment by scottbell** [comment]
### Testing Notes
1. Create a new Derived Telemetry object
2. Drop a couple of SWGs on it
3. Change the parameter names from a to x, and b to y
4. Add a [simple math.js expression](https://mathjs.org/examples/index.html): x*y - ensure expression is valid. Also check for math constants like `sqrt(x*y+pi)`
5. Change the x parameter to b. ensure an  invalid reference error is displayed. Change back to x.
6. Change expression to a*b - ensure expression is marked invalid
7. Change back to a*b, and add some test values to the parameters (e.g., 2 and 5), then toggle "Apply Test Data". Ensure the output matches the multiplication.
8. Go to the inspector tab in edit mode, and change the output format to `%0.2f` and save. Ensure floating point is formatted to only two decimals places in the output.
9. Untoggle "Apply Test Data" and put time conductor in real time mode. Ensure "Current Output" has a changing number that looks reasonable.
10. Drop Derived telemetry into an overlay plot along with the SWGs. Ensure both historical and realtime data plots.

**Comment by unlikelyzero** [comment]
Needs developer review but the tests and a11y look great. I made some comments.

Also we need to create good release notes and be sure to call this experimental. I went ahead and moved this to the 4.1.0 release

**Comment by charlesh88** [comment]
### Reference Images
![Screenshot 2024-11-14 at 10 08 18 AM](https://github.com/user-attachments/assets/d2bdd9f2-539f-4943-adf1-caf462a34f76)
![Screenshot 2024-11-14 at 10 07 47 AM](https://github.com/user-attachments/assets/3c721fcd-33ca-4598-8f2e-e00e8215bd78)
![Screenshot 2024-11-14 at 10 07 14 AM](https://github.com/user-attachments/assets/6a379f24-99f5-4fb1-96f9-62d63e194544)
![Screenshot 2024-11-14 at 10 07 07 AM](https://github.com/user-attachments/assets/db3c27a1-007e-4136-adab-bb784026db4b)

**Comment by charlesh88** [comment]
I've finished front-end sanding and shimming. @scottbell there were some minor markup changes with some v-ifs moving around a bit and some consolidation of containers. I put it through the wringer myself, but could you have a look and make sure I didn't break something? 

Otherwise, this is ready for review.

**Comment by scottbell** [comment]
@charlesh88 I did a cursory look (made a derived telemetry, testing good & bad equations, etc.) and it seemed to work well. FYI, I did cherry-pick your new commit over to the [telemetry-comps](https://github.com/nasa/openmct/tree/telemetry-comps) branch that has the [PR](https://github.com/nasa/openmct/pull/7815) for this.

**Comment by shefalijoshi** [comment]
Fixed Failing test:
a == 0 (when a is undefined)
a == 1 (when a is 'true')

<img width="197" height="287" alt="Image" src="https://github.com/user-attachments/assets/f688bbcc-c428-4f08-9e84-d762670fda92" />

<img width="182" height="285" alt="Image" src="https://github.com/user-attachments/assets/2295be21-8f04-4845-ba95-14ab7bbff809" />

Variations of the same:

<img width="236" height="267" alt="Image" src="https://github.com/user-attachments/assets/aa068777-9bd9-4efd-9e19-c8597ecde3ed" />

**Comment by davetsay** [comment]
- there is no derived telemetry icon
- there also is no icon for scatter plots
- expression validation does not fully work
  - repro
    1. follow steps to ref x and y, and make the expression a*b (expression invalid).
    2. change ref x to a and tab off (expression valid, should be invalid since b is not defined)

<img width="825" height="259" alt="Image" src="https://github.com/user-attachments/assets/7ddd1c1f-37f4-492a-991b-0578bcf089a8" />
